"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ComponentType = void 0;
var ComponentType;
(function (ComponentType) {
    ComponentType["INPUT"] = "input";
    ComponentType["BUTTON"] = "button";
    ComponentType["SELECT"] = "select";
    ComponentType["TEXTAREA"] = "textarea";
    ComponentType["DIV"] = "div";
    ComponentType["SPAN"] = "span";
    ComponentType["LABEL"] = "label";
    ComponentType["FORM"] = "form";
    ComponentType["TABLE"] = "table";
    ComponentType["TR"] = "tr";
    ComponentType["TD"] = "td";
    ComponentType["TH"] = "th";
    ComponentType["UL"] = "ul";
    ComponentType["OL"] = "ol";
    ComponentType["LI"] = "li";
    ComponentType["NAV"] = "nav";
    ComponentType["HEADER"] = "header";
    ComponentType["FOOTER"] = "footer";
    ComponentType["ARTICLE"] = "article";
    ComponentType["SECTION"] = "section";
    ComponentType["ASIDE"] = "aside";
    ComponentType["H1"] = "h1";
    ComponentType["H2"] = "h2";
    ComponentType["H3"] = "h3";
    ComponentType["H4"] = "h4";
    ComponentType["H5"] = "h5";
    ComponentType["H6"] = "h6";
    ComponentType["P"] = "p";
    ComponentType["IMG"] = "img";
    ComponentType["A"] = "a";
    ComponentType["IFRAME"] = "iframe";
    ComponentType["CANVAS"] = "canvas";
    ComponentType["SVG"] = "svg";
    ComponentType["VIDEO"] = "video";
    ComponentType["AUDIO"] = "audio";
    ComponentType["LINK"] = "link";
    ComponentType["SCRIPT"] = "script";
})(ComponentType || (exports.ComponentType = ComponentType = {}));
//# sourceMappingURL=html-generator.model.js.map